### ISSUE TITLE
🐛fix: file_upload when contents is empty msg is an invalid JSON

### ISSUE THREAD

**Issue by SantiagoGaonaC** [hawks-atlanta/gateway-java#64]
When a _fileContent_ with _length = 0_ is passed it enters the next if and returns a response invalidates the **Gateway**, the records by console are:
**Error:** `org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]`

**img:**
![image](https://github.com/hawks-atlanta/gateway-java/assets/53282017/679850f7-9574-493a-a30b-ebd2908178fd)

**Reference code:**
https://github.com/hawks-atlanta/gateway-java/blob/59506eb2fc4522ba27018f40af730d37402a730f/app/src/main/java/gateway/controller/CtrlFileUpload.java#L32-L36

Property names must be enclosed in double quotation marks, followed by a colon, and property values must also be enclosed in double quotation marks 📝
@PedroChaparro

**Comment by Woynert** [comment]
Thanks! will look into it

**Comment by PedroChaparro** [comment]
> Property names must be enclosed in double quotation marks, followed by a colon, and property values must also be enclosed in double quotation marks 📝 @PedroChaparro

I'm not part of the gateway development team @SantiagoGaonaC.

**Comment by Woynert** [comment]
About this string:

```
"{\"fileContent: must not be empty\"}";
```

It is not supposed to be JSON, the gateway returns SOAP objects. It's a string with errors from [Jakarta](https://beanvalidation.org/3.0/) (our field validator).

It contains a list of strings for the errors found in the validation. For example, when calling `file_upload` with:

- `fileName` as `Null` and
- `fileContent` as `Null`

you will get:

```
'{"fileContent: must not be null","fileName: must not be empty"}'
```

The curly brackets `{}` we add them in purpose, so I guess that's why there is some confusion. I think I'm gonna remove them so that the end result would be:

Single error:

```
fileContent: must not be null
```

Multiple errors:

```
fileContent: must not be null,fileName: must not be empty
```

___

About the error message you mention:

```
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

I can't reproduce it with the steps you listed.

**Comment by Woynert** [comment]
This PR fixes the style issue https://github.com/hawks-atlanta/gateway-java/pull/73
Let me know if you can reproduce your error.

**Comment by SilviaPabon** [comment]
@SantiagoGaonaC Hi, were you able to test the changes/fixes made by @Woynert? 🤔

**Comment by SantiagoGaonaC** [comment]
The changes are correct for when a contentFile is sent with null, anyway before sending it from the proxy this field is checked, I just tested it and it returns:

```json
{
    "code": 400,
    "msg": "{\"fileContent: must not be null\"}",
    "error": true
}
```
Thanks!!
